# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170926_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timetamp',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
    ]
