# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
    ]
